DEFAULT_CONFIDENCE_THRESHOLD = 0.3
DEFAULT_IOU_THRESHOLD = 0.45
DEFAULT_MIN_BOX_AREA_RATIO = 0.0005
DEFAULT_INFERENCE_IMG_SIZE = 480

CONFIDENCE_THRESHOLD = DEFAULT_CONFIDENCE_THRESHOLD
IOU_THRESHOLD = DEFAULT_IOU_THRESHOLD
FRAME_SKIP_CAMERA = 2
MIN_BOX_AREA_RATIO = DEFAULT_MIN_BOX_AREA_RATIO
INFERENCE_IMG_SIZE = DEFAULT_INFERENCE_IMG_SIZE
DEFAULT_WIDTH = 640
DEFAULT_HEIGHT = 480
TRACK_MATCH_THRESHOLD = 45.0
REACQUIRE_MATCH_THRESHOLD = 38.0
TARGET_MEMORY_FRAMES = 90
TRACK_UNIQUENESS_MARGIN = 7.0
REACQUIRE_UNIQUENESS_MARGIN = 12.0
MIN_REACQUIRE_AREA_RATIO = 0.45
MAX_REACQUIRE_CENTER_SHIFT_RATIO = 0.45


def reset_runtime_config():
    global CONFIDENCE_THRESHOLD, IOU_THRESHOLD, MIN_BOX_AREA_RATIO, INFERENCE_IMG_SIZE

    CONFIDENCE_THRESHOLD = DEFAULT_CONFIDENCE_THRESHOLD
    IOU_THRESHOLD = DEFAULT_IOU_THRESHOLD
    MIN_BOX_AREA_RATIO = DEFAULT_MIN_BOX_AREA_RATIO
    INFERENCE_IMG_SIZE = DEFAULT_INFERENCE_IMG_SIZE


def apply_runtime_overrides(
    confidence_threshold=None,
    iou_threshold=None,
    min_box_area_ratio=None,
    inference_img_size=None,
):
    global CONFIDENCE_THRESHOLD, IOU_THRESHOLD, MIN_BOX_AREA_RATIO, INFERENCE_IMG_SIZE

    reset_runtime_config()

    if confidence_threshold is not None:
        CONFIDENCE_THRESHOLD = float(confidence_threshold)
    if iou_threshold is not None:
        IOU_THRESHOLD = float(iou_threshold)
    if min_box_area_ratio is not None:
        MIN_BOX_AREA_RATIO = float(min_box_area_ratio)
    if inference_img_size is not None:
        INFERENCE_IMG_SIZE = int(inference_img_size)
